name: Build VSIX
on:
  push: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore
      run: msbuild Abs.Ssms.TabColoring.sln /t:Restore /m /v:m

    - name: Build (Release)
      run: msbuild Abs.Ssms.TabColoring.sln /t:Build /p:Configuration=Release /m /v:m /p:GenerateVsixContainer=true

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: Abs.Ssms.TabColoring_vsix
        path: |
          **/bin/Release/*.vsix
