name: Build VSIX

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Ważne: klasyczny restore dla packages.config (VSIX wrapper korzysta z BuildTools z katalogu "packages")
      - name: NuGet restore (solution)
        run: nuget restore Abs.Ssms.TabColoring.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      # Budujemy całe solution, żeby $(SolutionDir) było ustawione i importy z packages działały
      - name: Build solution (Release) + BINLOG
        run: msbuild Abs.Ssms.TabColoring.sln /t:Rebuild /p:Configuration=Release /m /v:m /bl:msbuild.binlog

      - name: Show outputs (debug)
        shell: pwsh
        run: |
          Write-Host "=== Files in VSIX project bin/Release ==="
          Get-ChildItem -Path src/Abs.Ssms.TabColoring.Vsix/bin/Release -Recurse -ErrorAction SilentlyContinue |
            Format-Table FullName, Length
          Write-Host "=== Find *.vsix anywhere ==="
          Get-ChildItem -Path . -Recurse -Filter *.vsix -ErrorAction SilentlyContinue |
            ForEach-Object { Write-Host "FOUND VSIX: $($_.FullName)" }

      - name: Upload VSIX + binlog
        uses: actions/upload-artifact@v4
        with:
          name: vsix-and-logs
          path: |
            **/*.vsix
            msbuild.binlog
          if-no-files-found: error
