name: Build VSIX
on:
  push: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: NuGet restore (solution)
      run: msbuild Abs.Ssms.TabColoring.sln /t:Restore /m /v:m

    - name: Build (Release) + BINLOG
      run: msbuild Abs.Ssms.TabColoring.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /m /v:m /bl:msbuild.binlog /p:GenerateVsixContainer=true /p:CreateVsixContainer=true

    - name: Show outputs (debug)
      shell: pwsh
      run: |
        Write-Host "=== DIR bin\Release ==="
        Get-ChildItem -Path src/Abs.Ssms.TabColoring/bin/Release -Recurse -ErrorAction SilentlyContinue | Format-Table FullName, Length
        Write-Host "=== Find *.vsix anywhere ==="
        Get-ChildItem -Path . -Recurse -Filter *.vsix -ErrorAction SilentlyContinue | ForEach-Object {
          Write-Host "FOUND VSIX: $($_.FullName)"
        }
        Write-Host "=== Find *.pkgdef (diagnostic) ==="
        Get-ChildItem -Path . -Recurse -Filter *.pkgdef -ErrorAction SilentlyContinue | ForEach-Object {
          Write-Host "FOUND PKGDEF: $($_.FullName)"
        }

    - name: Upload VSIX + binlog
      uses: actions/upload-artifact@v4
      with:
        name: vsix-and-logs
        path: |
          **/*.vsix
          **/*.pkgdef
          msbuild.binlog

