name: Build VSIX
on:
  push: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Zapewnij MSBuild i Visual Studio 2022 z VSSDK
    - name: Setup Visual Studio (VSSDK)
      uses: microsoft/setup-visualstudio@v1
      with:
        vs-version: '>=17.9'
        components: |
          Microsoft.VisualStudio.Component.VSSDK
          Microsoft.Component.MSBuild

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: msbuild Abs.Ssms.TabColoring.sln /t:Restore /m /v:m

    - name: Build (Release)
      run: msbuild Abs.Ssms.TabColoring.sln /t:Build /p:Configuration=Release /m /v:m /p:GenerateVsixContainer=true

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: Abs.Ssms.TabColoring_vsix
        path: |
          **/bin/Release/*.vsix
