name: Build VSIX
on:
  push: { branches: [ main, master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: NuGet restore (solution)
      run: msbuild Abs.Ssms.TabColoring.sln /t:Restore /m /v:m

    - name: Build (Release) + BINLOG
      run: msbuild Abs.Ssms.TabColoring.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /m /v:m /bl:msbuild.binlog /p:GenerateVsixContainer=true /p:CreateVsixContainer=true

    - name: List VSIX paths (debug)
      shell: pwsh
      run: |
        Write-Host "Searching for VSIX files..."
        Get-ChildItem -Path . -Recurse -Filter *.vsix | ForEach-Object {
          Write-Host "FOUND VSIX: $($_.FullName)"
        }

    - name: Upload VSIX + binlog
      uses: actions/upload-artifact@v4
      with:
        name: vsix-and-logs
        path: |
          **/*.vsix
          msbuild.binlog
